import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.Time;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Zer0
 */
public class FromTo extends javax.swing.JFrame {
    
    DefaultTableModel model;
    String url = "jdbc:mysql://localhost:3306/airline?zeroDateTimeBehavior=convertToNull";
    String user = "root";
    String password = "beyblade";
    int flID;
    int n;
    String fromPlace,toPlace;
    /**
     * Creates new form FromTo
     */
    public FromTo() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         this.model = (DefaultTableModel)flightDetails.getModel();
          try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt = con.createStatement();
            String query = "SELECT * FROM Cities ORDER BY City";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
                String cityName = rs.getString("City");
                fromCB.addItem(cityName);
                toCB.addItem(cityName);
                
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error in connection");
        }
          
          for(int i=1;i<13;i++){
              monthCB.addItem(""+i);
           
               
                    for(int n = 1; n<=30;n++){
                    dateCB.addItem(""+n);
        }
    
          }
         
            
            
          
          
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        fromCB = new javax.swing.JComboBox<>();
        toCB = new javax.swing.JComboBox<>();
        dateCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        monthCB = new javax.swing.JComboBox<>();
        yearCB = new javax.swing.JComboBox<>();
        checkButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        flightDetailPanel = new javax.swing.JPanel();
        proceedBooking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightDetails = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        passengerDetailPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        sexText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passengerNumber = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nationalityText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        transactionPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        transText = new javax.swing.JTextField();
        boardingText = new javax.swing.JTextField();
        destinationText = new javax.swing.JTextField();
        flightDate = new javax.swing.JTextField();
        boardingTimeText = new javax.swing.JTextField();
        reachingTimeText = new javax.swing.JTextField();
        fareText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1186, 502));
        setMinimumSize(new java.awt.Dimension(1200, 555));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1196, 548));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setFont(new java.awt.Font("Trajan Pro 3", 0, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("_");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1080, 10, 50, 23);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Trajan Pro 3", 0, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1139, 10, 50, 23);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 255, 255))));
        jPanel1.setOpaque(false);

        fromCB.setBackground(new java.awt.Color(0, 204, 204));
        fromCB.setForeground(new java.awt.Color(255, 255, 255));
        fromCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-From-" }));
        fromCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromCBActionPerformed(evt);
            }
        });

        toCB.setBackground(new java.awt.Color(0, 204, 204));
        toCB.setForeground(new java.awt.Color(255, 255, 255));
        toCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-To-" }));

        dateCB.setBackground(new java.awt.Color(0, 204, 204));
        dateCB.setForeground(new java.awt.Color(255, 255, 255));
        dateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD" }));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date :");

        monthCB.setBackground(new java.awt.Color(0, 204, 204));
        monthCB.setForeground(new java.awt.Color(255, 255, 255));
        monthCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM" }));
        monthCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthCBActionPerformed(evt);
            }
        });

        yearCB.setBackground(new java.awt.Color(0, 204, 204));
        yearCB.setForeground(new java.awt.Color(255, 255, 255));
        yearCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YYYY", "2017" }));

        checkButton.setBackground(new java.awt.Color(0, 0, 118));
        checkButton.setForeground(new java.awt.Color(255, 255, 255));
        checkButton.setText("Check");
        checkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enquiry");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fromCB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(toCB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(yearCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(monthCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(checkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel11)))
                .addGap(12, 18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(checkButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 150, 291, 169);

        parentPanel.setOpaque(false);
        parentPanel.setLayout(new java.awt.CardLayout());

        flightDetailPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 255, 255), new java.awt.Color(51, 255, 255)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(0, 204, 204), new java.awt.Color(0, 0, 204))));
        flightDetailPanel.setOpaque(false);
        flightDetailPanel.setLayout(null);

        proceedBooking.setBackground(new java.awt.Color(0, 0, 102));
        proceedBooking.setForeground(new java.awt.Color(255, 255, 255));
        proceedBooking.setText("Proceed To Booking");
        proceedBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedBookingActionPerformed(evt);
            }
        });
        flightDetailPanel.add(proceedBooking);
        proceedBooking.setBounds(330, 375, 195, 66);

        flightDetails.setBackground(new java.awt.Color(0, 0, 0));
        flightDetails.setForeground(new java.awt.Color(0, 255, 255));
        flightDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Flight Date", "Departure Time", "Arrival Time", "Aircraft No.", "Fare", "Seats Available"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        flightDetails.setGridColor(new java.awt.Color(0, 0, 153));
        flightDetails.setSelectionBackground(new java.awt.Color(255, 255, 255));
        flightDetails.setSelectionForeground(new java.awt.Color(0, 0, 153));
        jScrollPane1.setViewportView(flightDetails);

        flightDetailPanel.add(jScrollPane1);
        jScrollPane1.setBounds(17, 82, 849, 275);

        jLabel12.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Flight Details");
        flightDetailPanel.add(jLabel12);
        jLabel12.setBounds(360, 20, 210, 30);

        parentPanel.add(flightDetailPanel, "card2");

        passengerDetailPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102), new java.awt.Color(0, 204, 255)), javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 255, 255))));
        passengerDetailPanel.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phone No.");

        ageText.setBackground(new java.awt.Color(147, 207, 255));

        confirmButton.setBackground(new java.awt.Color(0, 0, 153));
        confirmButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        sexText.setBackground(new java.awt.Color(147, 207, 255));

        emailText.setBackground(new java.awt.Color(147, 207, 255));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email-ID");

        passengerNumber.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. of Passengers");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nationality");

        nationalityText.setBackground(new java.awt.Color(147, 207, 255));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");

        nameText.setBackground(new java.awt.Color(147, 207, 255));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age");

        phoneText.setBackground(new java.awt.Color(147, 207, 255));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sex");

        jLabel13.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Passenger Details");

        javax.swing.GroupLayout passengerDetailPanelLayout = new javax.swing.GroupLayout(passengerDetailPanel);
        passengerDetailPanel.setLayout(passengerDetailPanelLayout);
        passengerDetailPanelLayout.setHorizontalGroup(
            passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passengerDetailPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(passengerDetailPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ageText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nationalityText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(passengerDetailPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passengerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passengerDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(254, 254, 254))
        );
        passengerDetailPanelLayout.setVerticalGroup(
            passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passengerDetailPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(passengerNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sexText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(passengerDetailPanelLayout.createSequentialGroup()
                        .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nationalityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(passengerDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        parentPanel.add(passengerDetailPanel, "card3");

        transactionPanel.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TransactionID:");

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Boarding At:");

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Flight date:");

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Boarding time:");

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Reaching time:");

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total fare (in Rs.):");

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Destination:");

        transText.setEditable(false);
        transText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        transText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        transText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        transText.setMinimumSize(new java.awt.Dimension(9, 29));
        transText.setOpaque(false);
        transText.setPreferredSize(new java.awt.Dimension(9, 29));

        boardingText.setEditable(false);
        boardingText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        boardingText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        boardingText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        boardingText.setMinimumSize(new java.awt.Dimension(9, 29));
        boardingText.setOpaque(false);
        boardingText.setPreferredSize(new java.awt.Dimension(9, 29));

        destinationText.setEditable(false);
        destinationText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        destinationText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        destinationText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        destinationText.setMinimumSize(new java.awt.Dimension(9, 29));
        destinationText.setOpaque(false);
        destinationText.setPreferredSize(new java.awt.Dimension(9, 29));

        flightDate.setEditable(false);
        flightDate.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        flightDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        flightDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        flightDate.setMinimumSize(new java.awt.Dimension(9, 29));
        flightDate.setOpaque(false);
        flightDate.setPreferredSize(new java.awt.Dimension(9, 29));
        flightDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightDateActionPerformed(evt);
            }
        });

        boardingTimeText.setEditable(false);
        boardingTimeText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        boardingTimeText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        boardingTimeText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        boardingTimeText.setMinimumSize(new java.awt.Dimension(9, 29));
        boardingTimeText.setOpaque(false);
        boardingTimeText.setPreferredSize(new java.awt.Dimension(9, 29));
        boardingTimeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardingTimeTextActionPerformed(evt);
            }
        });

        reachingTimeText.setEditable(false);
        reachingTimeText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        reachingTimeText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        reachingTimeText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        reachingTimeText.setMinimumSize(new java.awt.Dimension(9, 29));
        reachingTimeText.setOpaque(false);
        reachingTimeText.setPreferredSize(new java.awt.Dimension(9, 29));
        reachingTimeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reachingTimeTextActionPerformed(evt);
            }
        });

        fareText.setEditable(false);
        fareText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        fareText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fareText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        fareText.setMinimumSize(new java.awt.Dimension(9, 29));
        fareText.setOpaque(false);
        fareText.setPreferredSize(new java.awt.Dimension(9, 29));
        fareText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fareTextActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("New Transaction");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 153));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit Application");
        jButton2.setMaximumSize(new java.awt.Dimension(129, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(129, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Transaction Details");

        javax.swing.GroupLayout transactionPanelLayout = new javax.swing.GroupLayout(transactionPanel);
        transactionPanel.setLayout(transactionPanelLayout);
        transactionPanelLayout.setHorizontalGroup(
            transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionPanelLayout.createSequentialGroup()
                .addGroup(transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionPanelLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transactionPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel18))
                        .addGap(82, 82, 82)
                        .addGroup(transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boardingText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinationText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flightDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boardingTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reachingTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fareText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addGap(144, 144, 144))
        );
        transactionPanelLayout.setVerticalGroup(
            transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel20)
                .addGap(45, 45, 45)
                .addGroup(transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionPanelLayout.createSequentialGroup()
                        .addGroup(transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transactionPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(transactionPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transactionPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(transactionPanelLayout.createSequentialGroup()
                        .addComponent(transText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boardingText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(destinationText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(flightDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boardingTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reachingTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(transactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fareText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        parentPanel.add(transactionPanel, "card4");

        getContentPane().add(parentPanel);
        parentPanel.setBounds(321, 56, 883, 459);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-440, 0, 1670, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButtonActionPerformed
        int fromIndex = fromCB.getSelectedIndex();
         fromPlace = fromCB.getItemAt(fromIndex);
        
        int toIndex = toCB.getSelectedIndex();
         toPlace = toCB.getItemAt(toIndex);
        
        parentPanel.removeAll();
        parentPanel.add(flightDetailPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt = con.createStatement();
            String query = "SELECT flid,flightdate,departuretime,arrivaltime,aircraft,netfare,availability FROM flight f,route r "
                    + "WHERE f.RouteID=r.RID AND r.Airport=\""+fromPlace+"\" AND r.Destination=\""+toPlace+"\";";
            String query1 = "SELECT *FROM flight;";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
                int FlID = rs.getInt("FlID");
                Date flightDate = rs.getDate("FlightDate");
                Time departureTime = rs.getTime("DepartureTime");
                Time arrivalTime = rs.getTime("ArrivalTime");
                int aircraftNo = rs.getInt("Aircraft");
                int fare = rs.getInt("Netfare");
                int availability = rs.getInt("Availability");
                
                model.addRow(new Object[]{
                    FlID, flightDate, departureTime,arrivalTime, aircraftNo, fare, availability
                });
           
            }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error in connection");
        }
    }//GEN-LAST:event_checkButtonActionPerformed

    private void monthCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthCBActionPerformed
      int i = monthCB.getSelectedIndex();
        if(i==1 || i==3 || i==5 || i==8 || i==10 || i==12){
            dateCB.removeAllItems();
                  for(int n = 1; n<=31;n++){    
                    dateCB.addItem(""+n);
                 } 
        }
        
        else
            if(i==4 || i==6 || i==7 || i==9 || i==11){
                 dateCB.removeAllItems();
            }
                for(int n = 1; n<=30;n++){             
                 
                  dateCB.addItem(""+n);
            }
        int index = yearCB.getSelectedIndex();
        int year = Integer.parseInt(yearCB.getItemAt(index));
        if(year%4==0 && i==2){
             dateCB.removeAllItems();
                  for(int n = 1; n<=29;n++){    
                    dateCB.addItem(""+n);
                 } 
        }
        else
            if(i==2){
                dateCB.removeAllItems();
                  for(int n = 1; n<=28;n++){    
                    dateCB.addItem(""+n);
                 } 
            }
                
    }//GEN-LAST:event_monthCBActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
      String name = nameText.getText();
      int age = Integer.parseInt(ageText.getText());
      char sex = sexText.getText().toUpperCase().charAt(0);
      String nationality = nationalityText.getText();
      String phno = phoneText.getText();
      String emailID = emailText.getText();
      int netFare;
      try {
        passengerNumber.commitEdit();
      } catch ( java.text.ParseException e ) {  }
        int passengerNo = (Integer) passengerNumber.getValue();
     
      
       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt = con.createStatement();
            String queryContact = "INSERT INTO contacts (Email_ID, Ph_no) VALUES('"
                    +emailID+"','"+phno+"');";
            stmt.executeUpdate(queryContact);
            String queryPassenger = "INSERT INTO passengers "
                    + "(Name,Age,Sex,Nationality,Contacts,No_of_Passengers) VALUES('"
                    + name+"',"+age+",'"+sex+"','"+nationality+"',"
                    + "(SELECT CnID from contacts WHERE Ph_no="+phno+"),"
                    + passengerNo + ");";
            stmt.executeUpdate(queryPassenger);
            
            String queryTransaction = "INSERT INTO transactions"
                    + "(BookingDate,DepartureDate,Passenger,No_of_Passengers,Flight,TotalAmount) VALUES("
                    + "CURDATE(),(SELECT FlightDate FROM flight WHERE FlID ="+flID+"),"
                    + "(SELECT PsID from passengers WHERE Contacts = "
                    + "(SELECT CnID FROM contacts WHERE Email_ID ='"+emailID+"' AND Ph_no='"+phno+"')),"
                    + passengerNo+","+flID+",(SELECT NetFare FROM flight WHERE FlID="+flID+")*"+passengerNo+");";            
            stmt.executeUpdate(queryTransaction);
            
            String queryFlight = "UPDATE flight SET Availability = Availability - "+ passengerNo + " WHERE FlID ="+flID+";";
            stmt.executeUpdate(queryFlight);
        
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error in connection");
        }

       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, password);
            Statement stmt = con.createStatement();
              String queryTrans = "SELECT * FROM transactions;";
            ResultSet rs = stmt.executeQuery(queryTrans);
            
            rs.last();
            int transID = rs.getInt(1);
            Date boardingDate = rs.getDate("DepartureDate");            
            int fare = rs.getInt("totalamount");
            
            String queryNetFare = "SELECT * FROM flight;";
            ResultSet rs1 = stmt.executeQuery(queryNetFare);
            
            rs1.last();
            netFare = rs1.getInt("NetFare");
            Time boardingTime = rs1.getTime("DepartureTime");
            Time reachingTime = rs1.getTime("arrivaltime");
          
            parentPanel.removeAll();
            parentPanel.add(transactionPanel);
            parentPanel.repaint();
            parentPanel.revalidate();
            jPanel1.removeAll();
            jPanel1.setVisible(false);
            
            transText.setText(""+transID);
            boardingText.setText(fromPlace);
            destinationText.setText(toPlace);
            flightDate.setText(""+boardingDate);
            boardingTimeText.setText(""+boardingTime);
            reachingTimeText.setText(""+reachingTime);
            fareText.setText(""+fare);
            
       }catch(Exception f){
           f.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error in connection");
       }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void fromCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromCBActionPerformed

    private void proceedBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedBookingActionPerformed

        flID = (Integer) model.getValueAt(flightDetails.getSelectedRow(), 0);

        parentPanel.removeAll();
        parentPanel.add(passengerDetailPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_proceedBookingActionPerformed

    private void flightDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightDateActionPerformed

    private void boardingTimeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardingTimeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boardingTimeTextActionPerformed

    private void reachingTimeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reachingTimeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reachingTimeTextActionPerformed

    private void fareTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fareTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fareTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       new FromTo().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 this.setState(Frame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromTo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromTo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageText;
    private javax.swing.JTextField boardingText;
    private javax.swing.JTextField boardingTimeText;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JComboBox<String> dateCB;
    private javax.swing.JTextField destinationText;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField fareText;
    private javax.swing.JTextField flightDate;
    private javax.swing.JPanel flightDetailPanel;
    private javax.swing.JTable flightDetails;
    private javax.swing.JComboBox<String> fromCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> monthCB;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField nationalityText;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JPanel passengerDetailPanel;
    private javax.swing.JSpinner passengerNumber;
    private javax.swing.JTextField phoneText;
    private javax.swing.JButton proceedBooking;
    private javax.swing.JTextField reachingTimeText;
    private javax.swing.JTextField sexText;
    private javax.swing.JComboBox<String> toCB;
    private javax.swing.JTextField transText;
    private javax.swing.JPanel transactionPanel;
    private javax.swing.JComboBox<String> yearCB;
    // End of variables declaration//GEN-END:variables
}
